<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/InterLan.Contracts/InterLan.Contracts.csproj" />
    <ProjectReference Include="../../src/InterLan.Infrastructure/InterLan.Infrastructure.csproj" />
  </ItemGroup>
</Project>
